---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-database-config
data:
  URL: jdbc:h2:tcp://database:1521/payment
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: payment-storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: payment-storage-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: payment-storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: payment-storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: payment-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-storage-service
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-storage-service
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - name: payment-storage-service
          image: io.github.jonarzz/payment-storage-service:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_LOG_LEVEL
              value: INFO
            - name:  QUARKUS_LIQUIBASE_MIGRATE_AT_START
              value: 'true' # set to 'false' to skip schema creation (better startup time)
            - name:  QUARKUS_LIQUIBASE_CLEAN_AT_START
              value: 'false' # set to 'true' to recreate the schema
            # JMS
            - name: JMS_PAYMENT_DESTINATION_REGISTER
              value: payment/register/v1
            - name: JMS_PAYMENT_DESTINATION_STORE
              value: payment/store/v1
            - name: JMS_PAYMENT_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: QUARKUS_ARTEMIS_URL
              value: tcp://jms-broker:61616
            - name: QUARKUS_ARTEMIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: jms-username
            - name: QUARKUS_ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: jms-password
            # database
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-database-config
                  key: URL
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: database-username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: database-password
