apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artemis-journal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jms-broker
  labels:
    app: jms-broker
spec:
  ports:
    - name: jms
      port: 61616
      targetPort: 61616
    - name: ui
      port: 8161
      targetPort: 8161
  selector:
    app: jms-broker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artemis-etc
data:
  jolokia-access.xml: |
    <restrict>
      <cors>
        <strict-checking/>
        <allow-origin>*://0.0.0.0*</allow-origin>
        <allow-origin>*://localhost*</allow-origin>
      </cors>
    </restrict>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jms-broker
  labels:
    app: jms-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jms-broker
  template:
    metadata:
      labels:
        app: jms-broker
    spec:
      containers:
        - image: quay.io/artemiscloud/activemq-artemis-broker:1.0.6
          imagePullPolicy: IfNotPresent
          name: jms-broker
          env:
            # TODO login and password as k8s Secret
            - name: AMQ_USER
              value: artemis
            - name: AMQ_PASSWORD
              value: artemis
            - name: AMQ_EXTRA_ARGS
              value: --nio --http-host 0.0.0.0 --host 0.0.0.0 --queues paymentQueue # --require-login
          ports:
            - containerPort: 61616
              name: jms
            - containerPort: 8161
              name: ui
          volumeMounts:
            - name: journal
              mountPath: ~/broker/data/journal
            - name: jolokia-access
              mountPath: ~/broker/etc
      volumes:
        - name: journal
          persistentVolumeClaim:
            claimName: artemis-journal
        - name: jolokia-access
          configMap:
            name: artemis-etc
            items:
              - key: jolokia-access.xml
                path: jolokia-access.xml